spring:
  application:
    name: overload

logging:
  level:
    root: WARN
    com.mats.overload: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] [%X{requestId}] %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers